// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1SLYKRNnVwyUEfqBhlc18FdH-D4fMS1s',
    appId: '1:448833194889:web:0205a99ea2d454718fef58',
    messagingSenderId: '448833194889',
    projectId: 'khoa-b04cc',
    authDomain: 'khoa-b04cc.firebaseapp.com',
    databaseURL: 'https://khoa-b04cc-default-rtdb.firebaseio.com',
    storageBucket: 'khoa-b04cc.firebasestorage.app',
    measurementId: 'G-0P8Q07J9VS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWqIyMB9Jonooy-UedjFjEznWJf14Dxas',
    appId: '1:448833194889:android:9514037fce3b6fe78fef58',
    messagingSenderId: '448833194889',
    projectId: 'khoa-b04cc',
    databaseURL: 'https://khoa-b04cc-default-rtdb.firebaseio.com',
    storageBucket: 'khoa-b04cc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1SLYKRNnVwyUEfqBhlc18FdH-D4fMS1s',
    appId: '1:448833194889:web:b9729b3a344236818fef58',
    messagingSenderId: '448833194889',
    projectId: 'khoa-b04cc',
    authDomain: 'khoa-b04cc.firebaseapp.com',
    databaseURL: 'https://khoa-b04cc-default-rtdb.firebaseio.com',
    storageBucket: 'khoa-b04cc.firebasestorage.app',
    measurementId: 'G-MN2HEYWT4R',
  );
}
